### PR TITLE
[3|CBH - Organization Management Page] Edit organization #35

### LINKED ISSUE #35: [3|CBH - Organization Management Page] Edit organization
<h2 align="center"> 🍰 Appetite 🍰 </h2>
<div align="center">

| Property | Value |
|:-------|:------:|
| Points | 15 points |
| Difficulty rating | ★★★☆☆ | 
| Maximum Assignees | 3 person | 

</div>

🤔 Problem Statement
------------------------------------------
image

Create the feature of editing existing organizations, where CBH is able to change organization's information, delete org, enable/disable org, reset password of HR.

🧪 Required Tests
-------------------------------------
Mainly screenshot tests.
Review the [Code & Testing Guidelines](https://google.com/) for more info.

⚠️ Careful about:
-------------------
No major rabbit holes identified. But always be careful with scope creep!

🤖 Technologies focused on in this feature
---------------------------
- React
- Tailwind
- Shadcn
- NextJS
- Supabase/PostGresQL

### PR DESCRIPTION
**Pull request by Sneezy-w**
Closes #35

### CODE REVIEW

**Comment by devanmolsharma** [comment]
can you please link it to the edit button at /cbh/organization-

**Comment by Sneezy-w** [comment]
@devanmolsharma Now it's fixed. The data will be retrieved from the database

**Comment by Sneezy-w** [comment]
@devanmolsharma Now The conflict has also been resolved

**Comment by devanmolsharma** [comment]
Great Work

**Pull request merged**
