### PR TITLE
Style bounty Update Hamburger button Topic page

### PR DESCRIPTION
**Pull request by josedsegurav**
Style bounty:
http://localhost:3000/topic/1
Is not using the Hamburger menu

### CODE REVIEW

**Comment by Simpcyclassy** [comment]
Can you attach the issue number to this PR?

**Comment by yscpeak** [comment]
> @josedsegurav Can you attach the issue number to this PR?

[[4|Topic Detail Page] Hamburger Menu button](https://github.com/Builder-s-League/BuildersLeague-Edition1/issues/7#top)

**Comment by josedsegurav** [comment]
This is a bounty from the discord, I don't know if this has an issue number

**Comment by Ryan-L3** [comment]
@josedsegurav There is a type with the button. Please fix and recommit.

**Comment by josedsegurav** [comment]
Fixed and commited

**Comment by LeopoldXing** [comment]
project failed to compile, '@/components/MenuDrawer' is not recognize in src/app/topic/[id]/page

**Pull request merged**
